### ISSUE TITLE
Could not load dynamic library 'cudart64_110.dll'

### ISSUE THREAD

**Issue by eterevsky** [cloudhan/jax-windows-builder#16]
I've installed this build, but I keep getting the "Could not load dynamic library 'cudart64_110.dll'" error even though I clearly see the dll in a directory on the PATH.

My configuration:

```
Windows 11 Home 21H2
Python: 3.10.7
CUDA: 11.1.0 (for Win10, there's no dedicated build for Win11)
CuDNN: cudnn-11.3-windows-x64-v8.2.1.32
jaxlib: jaxlib-0.3.14+cuda11.cudnn82-cp310-none-win_amd64.whl 
jax: 0.3.14
```

CUDA + CuDNN are installed in `c:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin` which is on the PATH.

Full error:

```
$ python
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
2022-09-18 11:52:21.036734: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-09-18 11:52:21.058690: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
```

**Comment by cloudhan** [comment]
Hmm, but it still seems to be that `cudart64_110.dll` is missing from `PATH`. Can you verify it by executing `cudart64_110.dll`?

In my PowerShell, when it is in `PATH`:
```console
(base) cloud@LAPTOP-GU603HR PS C:\Users\cloud
> cudart64_110.dll
ResourceUnavailable: Program 'cudart64_110.dll' failed to run: An error occurred trying to start process 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\bin\cudart64_110.dll' with working directory 'C:\Users\cloud'. 没有应用程序与此操作的指定文件有关联。At line:1 char:1
+ cudart64_110.dll
```

When it is not in `PATH`
```console
cudart64_110.dll: The term 'cudart64_110.dll' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
And I only obtain same WARN msg like yours in this case.

**Comment by eterevsky** [comment]
When I'm trying to run `curdart64_110.dll` I'm getting:

```
C:\Users\oleg>cudart64_110.dll
The system cannot execute the specified program.
```

or in git bash, where I usually use python:

```
$ cudart64_110.dll
bash: /c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/bin/cudart64_110.dll: cannot execute binary file: Exec format error
```

Based on this error it seems like it is found.

**Comment by cloudhan** [comment]
This is really a curious situation then. I tested it with my git bash with cuda 11.5 and 11.6 and it loads. Can you `export TF_CPP_MIN_LOG_LEVEL=0` in bash before launch python and see what the verbose log is?

**Comment by eterevsky** [comment]
I figured it out. My mistake was installing Python from Microsoft Store. When I re-installed Python from conda or directly via the python.org installer, everything worked like a charm.

Sorry for bothering you!
